AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy Pizzaria App com Docker Compose na EC2'

Parameters:
  KeyName:
    Description: Nome do Key Pair para acesso SSH
    Type: AWS::EC2::KeyPair::KeyName
    Default: gabrielm-keypair
  
  InstanceType:
    Description: Tipo de instancia EC2
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  
  GitHubRepo:
    Description: URL do repositorio GitHub
    Type: String
    Default: https://github.com/GabriellMarcos/proway-docker.git

Resources:
  # Security Group
  PizzariaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: pizzaria-sg
      GroupDescription: Security group para Pizzaria App
      SecurityGroupIngress:
        # SSH
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        # Frontend
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        # Backend
        - IpProtocol: tcp
          FromPort: 5001
          ToPort: 5001
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: pizzaria-sg

  # EC2 Instance
  PizzariaEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 - us-east-2
      SecurityGroups:
        - !Ref PizzariaSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Atualizar sistema
          yum update -y
          
          # Instalar Docker
          amazon-linux-extras install docker -y
          systemctl start docker
          systemctl enable docker
          usermod -a -G docker ec2-user
          
          # Instalar Docker Compose
          curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          
          # Instalar Git
          yum install git -y
          
          # Clonar repositorio
          cd /home/ec2-user
          git clone ${GitHubRepo} proway-docker
          cd proway-docker/pizzaria-app
          
          # Dar permissao ao script de deploy
          chmod +x deploy_pizzaria.sh
          
          # Executar deploy
          bash deploy_pizzaria.sh
          
          # Configurar cron para auto-update (a cada 5 minutos)
          echo "*/5 * * * * bash /home/ec2-user/proway-docker/pizzaria-app/deploy_pizzaria.sh >> /var/log/deploy_pizzaria.log 2>&1" | crontab -u ec2-user -
          
          # Criar arquivo de log
          touch /var/log/deploy_pizzaria.log
          chown ec2-user:ec2-user /var/log/deploy_pizzaria.log
          
      Tags:
        - Key: Name
          Value: pizzaria-app-server

Outputs:
  InstanceId:
    Description: ID da instancia EC2
    Value: !Ref PizzariaEC2
  
  PublicIP:
    Description: IP publico da instancia
    Value: !GetAtt PizzariaEC2.PublicIp
  
  FrontendURL:
    Description: URL do frontend
    Value: !Sub 'http://${PizzariaEC2.PublicIp}:8080'
  
  BackendURL:
    Description: URL do backend
    Value: !Sub 'http://${PizzariaEC2.PublicIp}:5001/api/pizzas'
  
  SSHCommand:
    Description: Comando para acessar via SSH
    Value: !Sub 'ssh -i ${KeyName}.pem ec2-user@${PizzariaEC2.PublicIp}'
